diccionario <- data.frame(
  Nombre_base = c(
    "NHC",
    "tipo_histologico",
    "localizacion_tumor",
    "sexo_hombre_mujer",
    "fecha_nacimiento",
    "fecha_diagnostico_ap",
    "edad_al_diagnostico",
    "ca_19_9_al_dx",
    "tamano_tumoral_al_dx_por_tc_diametro_mayor_en_cm",
    "metastasis_al_dx",
    "cirugia_intencion_curativa",
    "tipo_de_cirugia",
    "tamano_tumoral_pieza_quirurgica_cm",
    "numero_ganglios_resecados",
    "numero_adenopatias_positivas",
    "exitus",
    "fecha_exitus",
    "causa_exitus",
    "fecha_ultima_revision",
    "fecha_recogida_datos"
  ),
  
  Nombre_TFG = c(
    "Identificador paciente",
    "Tipo histológico",
    "Localización tumoral",
    "Sexo",
    "Fecha de nacimiento",
    "Fecha de diagnóstico",
    "Edad al diagnóstico",
    "CA 19-9 al diagnóstico",
    "Tamaño tumoral al diagnóstico",
    "Metástasis al diagnóstico",
    "Cirugía con intención curativa",
    "Tipo de cirugía",
    "Tamaño tumoral en pieza quirúrgica",
    "Número de ganglios resecados",
    "Número de adenopatías positivas",
    "Éxitus",
    "Fecha de éxitus",
    "Causa de éxitus",
    "Fecha última revisión",
    "Fecha recogida de datos"
  ),
  
  Tipo = c(
    "Identificador",
    "Categórica",
    "Categórica",
    "Categórica",
    "Fecha",
    "Fecha",
    "Continua",
    "Continua",
    "Continua",
    "Categórica",
    "Categórica",
    "Categórica",
    "Continua",
    "Continua",
    "Continua",
    "Categórica",
    "Fecha",
    "Categórica",
    "Fecha",
    "Fecha"
  ),
  
  Definicion = c(
    "Código único de identificación del paciente",
    "Clasificación histológica del tumor",
    "Localización anatómica del tumor primario",
    "Sexo biológico registrado en la historia clínica",
    "Fecha de nacimiento del paciente",
    "Fecha de diagnóstico anatomopatológico",
    "Edad calculada entre fecha de nacimiento y fecha de diagnóstico",
    "Valor sérico del marcador tumoral CA 19-9 al diagnóstico",
    "Diámetro tumoral máximo medido mediante TC al diagnóstico",
    "Presencia de enfermedad metastásica al diagnóstico",
    "Realización de cirugía con intención curativa",
    "Tipo de procedimiento quirúrgico realizado",
    "Diámetro tumoral máximo medido en la pieza quirúrgica",
    "Número total de ganglios resecados",
    "Número de adenopatías positivas identificadas en la pieza quirúrgica",
    "Estado vital del paciente durante el seguimiento",
    "Fecha de fallecimiento",
    "Causa del fallecimiento",
    "Fecha de última revisión clínica en pacientes vivos",
    "Fecha de recogida de datos"
  ),
  
  Codificacion = c(
    "Código numérico",
    "Adenocarcinoma / Adenocarcinoma mucinoso / Cistoadenocarcinoma / TNE",
    "Cabeza / cuerpo / cola / múltiples",
    "Hombre / mujer",
    "Formato fecha",
    "Formato fecha",
    "Años",
    "U/mL; 99999 = ausente",
    "cm; 99 = ausente",
    "No / Sí",
    "No / Sí",
    "Distal / DPC",
    "cm",
    "Número entero",
    "Número entero",
    "No / Sí",
    "Formato fecha",
    "Tumoral / complicación postqx / infecciosa / toxicidad / otros / desconocida",
    "Formato fecha",
    "Formato fecha"
  ),
  
  Unidad = c(
    "-",
    "-",
    "-",
    "-",
    "-",
    "-",
    "años",
    "U/mL",
    "cm",
    "-",
    "-",
    "-",
    "cm",
    "n",
    "n",
    "-",
    "-",
    "-",
    "-",
    "-"
  ),
  
  Momento = c(
    "Registro",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Diagnóstico",
    "Seguimiento",
    "Seguimiento",
    "Postquirúrgico",
    "Postquirúrgico",
    "Postquirúrgico",
    "Seguimiento",
    "Seguimiento",
    "Seguimiento",
    "Seguimiento",
    "Recolección de datos"
  ),
  
  Ausentes = c(
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "No",
    "99999 → NA",
    "99 → NA",
    "Desconocido",
    "No",
    "NA si no cirugía",
    "NA si no cirugía",
    "NA si no cirugía",
    "NA si no cirugía",
    "No",
    "NA si vivo",
    "Desconocido",
    "NA si éxitus",
    "No"
  )
)


knitr::kable(
  diccionario,
  caption = "Tabla A2. Diccionario de variables del estudio"
)

flextable(diccionario) %>%
  theme_booktabs() %>%
  bold(part = "header") %>%
  autofit()
